version: '3.9'

services:
  # web server with php and apache2
  web:
    build:
      context: .
      dockerfile: ./web/web.dockerfile
    container_name: ${APP_NAME}-web
    ports:
      - 80:80
    hostname: ${DOMAIN}
    volumes:
      - ./web/html:/var/www/html:delegated
    depends_on:
      - db
    restart: always
  
  # mysql db server
  db:
    image: mysql:8
    container_name: ${APP_NAME}-db
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./db:/var/lib/mysql:delegated
    restart: always
  
  # php my admin
  phpmyadmin:
    image: phpmyadmin:apache
    restart: always
    ports:
      - 8080:80
    hostname: ${DOMAIN}
    container_name: ${APP_NAME}-phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
    depends_on:
      - db

